version: '3.4'

services:

  offers.api:
    image: ${DOCKER_REGISTRY-}offersapi
    build:
      context: .
      dockerfile: src/Offers.Api/Dockerfile

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=quero@123
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"